### ISSUE TITLE
Website nees to move to HTTPS

### ISSUE THREAD

**Issue by KadeMorton** [aletheia-foundation/aletheia-foundation.github.io#18]
## I confirm:

- [x] I've read the [contributing guidelines](https://github.com/aletheia-foundation/aletheia-admin/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/aletheia-foundation/aletheia-admin/blob/master/CODE-OF-CONDUCT.md)
- [x] I've checked that this issue applies to this repo
- [x] I've checked the existing issues, no one else has reported this
- [x] I've got a clear and descriptive title for the issue 

---------------------------

## Suggest an enhancement - delete this section if not suggesting an enhancement

To make your enhancement suggestion as useful to others as possible, please consider the below and try to answer as many of them as possible:

* Provide a step-by-step description of the suggested enhancement in as many details as possible.
* Provide specific examples to demonstrate the steps. Include copy/pasteable snippets which you use in those examples, as Markdown code blocks if possible.
* Describe the current behaviour and explain which behaviour you expected to see instead and why.
* Include screenshots which help you demonstrate the steps or point out the part of Aletheia which the suggestion is related to.
* Explain why this enhancement would be useful to most Aletheia users.
* List some other applications where this enhancement exists.
* Specify which version of Aletheia you're using.
* Specify the name and version of the OS you're using.

### My response:
* The website currently uses HTTP, it needs to use HTTPS by default.
* Example
![image](https://user-images.githubusercontent.com/24201238/31840711-0ab4f694-b643-11e7-95ad-2df6e845677a.png)

![image](https://user-images.githubusercontent.com/24201238/31840606-9b3d4456-b642-11e7-853d-ffa0f4de24ce.png)
* current behaviour is traffic to the site is not encrypted and if we add in donation facilities, log ins etc these can be compromised. The behaviour required is using HTTPS, traffic to the site and any information submitted to the site will be encrypted which is why this upgrade would be useful.
* Examples of HTTPS
![image](https://user-images.githubusercontent.com/24201238/31840859-9df7efec-b643-11e7-9744-adb0a91a5cb7.png)
![image](https://user-images.githubusercontent.com/24201238/31840885-bc9f4b2a-b643-11e7-9c79-db027c3adfec.png)

**Comment by KadeMorton** [comment]
I did some searching, followed https://help.github.com/articles/securing-your-github-pages-site-with-https/ but found https was disabled due to using a custom domain. Further searching yielded https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/ and signed up for Cloudflare. Hopefully if I got everything right it should all be moved over in two days.

**Comment by mjashanks** [comment]
had a read of that....looks easy enough. However, I think it should probably be you or @roo2  that does it - as whoever does it will need access to the domain registrar. Then, on creating a Cloudflare account, I assume that you guys would want to hold the credentials for that as well.

**Comment by KadeMorton** [comment]
@mjashanks Yeah, I've changed the domain registrar and Cloudflare tells me it should be actioned soon. After creating the issue decided to look into it myself, should be sorted soon.

**Comment by KadeMorton** [comment]
Cloudflare have been super unhelpful and now I'm back from travelling will get back to sorting this out.

**Comment by KadeMorton** [comment]
Had another stab at this, will check in the morning if it's updated overnight. If it works there is another step to complete the rest of https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

**Comment by KadeMorton** [comment]
Another stab at fixing it, if didn't work I'll work through https://medium.freecodecamp.org/an-illustrated-guide-for-setting-up-your-website-using-github-cloudflare-5a7a11ca9465

**Comment by KadeMorton** [comment]
Dig commands to reference http://bsdwiki.reedmedia.net/wiki/Determine_who_is_responsible_for_a_DNS_zone.html

**Comment by KadeMorton** [comment]
Got it working
