### ISSUE TITLE
Add Patreon  to our website

### ISSUE THREAD

**Issue by KadeMorton** [aletheia-foundation/aletheia-foundation.github.io#19]
## I confirm:

- [x] I've read the [contributing guidelines](https://github.com/aletheia-foundation/aletheia-admin/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/aletheia-foundation/aletheia-admin/blob/master/CODE-OF-CONDUCT.md)
- [x] I've checked that this issue applies to this repo
- [x] I've checked the existing issues, no one else has reported this
- [x] I've got a clear and descriptive title for the issue 

---------------------------

## Suggest an enhancement - delete this section if not suggesting an enhancement

To make your enhancement suggestion as useful to others as possible, please consider the below and try to answer as many of them as possible:

* Provide a step-by-step description of the suggested enhancement in as many details as possible.
* Provide specific examples to demonstrate the steps. Include copy/pasteable snippets which you use in those examples, as Markdown code blocks if possible.
* Describe the current behaviour and explain which behaviour you expected to see instead and why.
* Include screenshots which help you demonstrate the steps or point out the part of Aletheia which the suggestion is related to.
* Explain why this enhancement would be useful to most Aletheia users.
* List some other applications where this enhancement exists.
* Specify which version of Aletheia you're using.
* Specify the name and version of the OS you're using.

### My response:

* We need a link to our Patreon page on our website https://www.patreon.com/Aletheia_f
* Would be nice if it could be placed here 
![image](https://user-images.githubusercontent.com/24201238/33519874-dff8c464-d814-11e7-8d3b-348a72e31e44.png)
* It's not there currently
* We need to generate funds to sustain the project
* N/A
* N/A
* N/A

**Comment by koltclassic** [comment]
https://github.com/aletheia-foundation/aletheia-foundation.github.io/pull/23

**Comment by KadeMorton** [comment]
I merged the pull request, however can't see the Patreon link.

**Comment by KadeMorton** [comment]
It's now working, closing off, thanks @koltclassic !
